# Hooks are defined in global config file located at ~/.config/ciallo/config.toml
# Example:
# [hook.hook_name.feishu]
# webhook_url = "url-to-feishu-bot"
#
# [hook.feishu.feishu]
# webhook_url = "url-to-feishu-bot"

[cmd.bench]
command = "cargo bench"
stdout = true # Default: true
stderr = true # Default: true
hooks = [ "hook_name", "feishu" ] # Default: []

[cmd.check]
command = "cargo check"
hooks = [ "feishu" ]
